### ISSUE TITLE
Consider adding additional getters in BAM

### ISSUE THREAD

**Issue by nh13** [brentp/hts-nim#15]
In addition to `reverse`, how about `forward`?  
In addition to `qcfail`, how about `pf`?

I really like what you have started in hts-nim, and I have found having the logically opposite getter (reverse vs. forward, paired vs fragment, mate_unmapped vs mate_mapped) to really powerful.  See the [scala BAM API](https://github.com/fulcrumgenomics/fgbio/blob/master/src/main/scala/com/fulcrumgenomics/bam/api/SamRecord.scala#L72-L230) in fgbio for some ideas to make it _much_ nicer than htsjdk or the htslib C-API.

**Comment by brentp** [comment]
I agree on the utility of this, but this is a case where I think matching the underlying API makes sense because it has become the way that most users are accustomed to deal with these things. Another reason I don't want to include is that because of [UFCS](https://en.wikipedia.org/wiki/Uniform_Function_Call_Syntax#Nim_programming_language), a user can create their own accessors, like:

```Nim
import hts 

proc forward*(f: Flag): bool {.inline.} =
  return not f.reverse

var b:Bam
b.open("K02209.disc.bam")

for r in b:
  if r.flag.forward:                                                            
    echo $r
```
which is working code. This is a trade-off between surface-area of the API I create/expose in `hts-nim` and the ergonomics of the library. I think that keeping the API small and letting the user define their own convenience functions is the mode to follow here.

**Comment by nh13** [comment]
As a NIM novice, this was really helpful.
